export enum Region {
  ABRUZZO = 'ABB',
  BASILICATA = 'BAS',
  CALABRIA = 'CAL',
  CAMPANIA = 'CAM',
  E_ROMAGNA = 'EMI',
  F_V_G = 'FRI',
  LAZIO = 'LAZ',
  LIGURIA = 'LIG',
  LOMBARDIA = 'LOM',
  MARCHE = 'MAR',
  MOLISE = 'MOL',
  PIEMONTE = 'PIE',
  PUGLIA = 'PUG',
  SARDEGNA = 'SAR',
  SICILIA = 'SIC',
  TOSCANA = 'TOS',
  T_A_A_T = 'TRT',
  T_A_A_B = 'TRB',
  UMBRIA = 'UMB',
  V_D_A = 'VAL',
  VENETO = 'VEN',
}
